### ISSUE TITLE
Do we still need this plugin?

### ISSUE THREAD

**Issue by gazay** [postcss/postcss-messages#17]
According to https://github.com/lydell/postcss-log-warnings/commit/4891e070779fe45c144a20d129ad00a0fe49fe1d by @lydell plugin `postcss-log-warnings` does almost same thing as this plugin. Do we still need this plugin for some reason or better to deprecate it in favor to `postcss-log-warnings`?

/cc @ai @MoOx

**Comment by ai** [comment]
`postcss-log-warnings` is a @davidtheclark plugin. and this display messages to console, not to browser. @lydell create a PR, but it wasn’t accepted.

**Comment by gazay** [comment]
Ah, now I see. Thank you.

**Comment by MoOx** [comment]
I think that this plugin have his place in the community. Maybe we should rename to postcss-browser-log-messages?
I have a bunch of improvement to push & think options to customize design is a cool thing.

Btw maybe @davidclark could move his repo under postcss org and rename to postcss-console-log-messages? 

I just add this two plugin into cssnext and think they are really must have plugins to communicate easily with  cssnext/plugin consumers.

**Comment by davidtheclark** [comment]
I'm be happy to move and rename the log-warnings plugin if you think it would better serve postcss users.

Also, I do think that @lydell has a plan for having two separate plugins, one for the console and one for the browser, without duplicating much code. See https://github.com/davidtheclark/postcss-log-warnings/pull/10 which was merged into log-warnings.

**Comment by ai** [comment]
@davidtheclark nice, I send you an invite to PostCSS org. I think that `postcss-log-warning` is very important to ecosystem

**Comment by davidtheclark** [comment]
Cool. I will try to get that done this weekend.
