### ISSUE TITLE
Add option to customize styles of the message box

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-messages#3]

**Comment by gazay** [comment]
I've added it here https://github.com/postcss/postcss-messages/commit/9fb218420d4af8f35c771a63bb99ca856799b83b, but I'm not a JS programmer and could mess with code style, can you please help and review it? Also ci is failing after my changes: https://travis-ci.org/postcss/postcss-messages/jobs/56995895.

/cc @ai, @MoOx

**Comment by gazay** [comment]
CI is not failing anymore, I've figured our that there were unnecessary semicolons.

**Comment by ai** [comment]
`styleKeys` is not a good solution. User may want to se some new style. It is better to add `style` key in options:

``` js
messages({
  style: {
    'box-shadow': '0 0 10px black'
  }
});
```

**Comment by ai** [comment]
BTW, options is a lack in UX. You should better think more about default options and styles, rather than add options for every case.

**Comment by gazay** [comment]
`styleKeys` here is excess code, firstly I thought to do it this way, but then I just set default styles and give users way to override or add new styles

**Comment by gazay** [comment]
Done
