### ISSUE TITLE
Check if existing AST doesn't already use `body:before`

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss-messages#4]
We might need to use `body:after` (with fixed position) if body:before is already used.
And throw a warning if we will override existing styles (if body:after & before are already used).

**Comment by gazay** [comment]
Good idea! I'll continue working on this lib in two days after my flight home

**Comment by ai** [comment]
Maybe we should use `html::before`, because it is used very rare.

**Comment by gazay** [comment]
I don't really know how to check if selector already in use, but I've added option to override selector and set `html:before` as default: https://github.com/postcss/postcss-messages/commit/e1d297de2794b960bd4eadf51560b535317f77ab

**Comment by ai** [comment]
@gazay you can check other selectors by:

``` js
var selector = 'html::before';
css.eachRule(function (rule) {
    if ( rule.selector === 'html:before' ||  rule.selector === 'html:before' ) {
        selector = 'html:after';
    }
});
```

**Comment by gazay** [comment]
Thank you, added checking in v0.2.1.

**Comment by lydell** [comment]
Just noting that no warning is thrown if if both `html::before` and `html::after` are used.
