### ISSUE TITLE
Release postcss-messages

### ISSUE THREAD

**Issue by ai** [postcss/postcss-messages#6]
PostCSS 4.1 is out and yor plugin is in [changelog](https://github.com/postcss/postcss/releases/tag/4.1.0), so we can release this package.
1. Change `"postcss": "~4.1.0"` in `package.json`.
2. Set version in `package.json` (`0.1.0` will be a good choice).
3. Add release to `ChangeLog.md`.
4. Publish release by `npm publish`.
5. Send a PR with yor plugin in Plugins/Others section in PostCSS README.md.

/cc @gazay

**Comment by gazay** [comment]
https://github.com/postcss/postcss/pull/276 done
