### ISSUE TITLE
Unify text format

### ISSUE THREAD

**Issue by ai** [postcss/postcss-messages#8]
@davidtheclark brings nice warning format to [postcss-log-warnings](https://github.com/davidtheclark/postcss-log-warnings).

Maybe we should use it here to?

**Comment by MoOx** [comment]
We can't have a lot of choice using `content`. Not sure we can enhance this a lot.

**Comment by gazay** [comment]
We have newline and spaces there so we can have similar indentation. But not colors yes.

**Comment by ai** [comment]
Yes, I talk about indentation and per file grouping.

**Comment by gazay** [comment]
Done https://github.com/postcss/postcss-messages/commit/98944a11779296fc2f1b4832180480eaac0043e1
